//ACTIONS FOR GATHERING USER INPUT
export const USER_BOOK_INPUT = 'USER_BOOK_INPUT';

//REDUX THUNK ACTIONS
export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
export const GET_BOOKS_FAIL = 'GET_BOOKS_FAIL';